### PR TITLE
Init Transformer

### PR DESCRIPTION
**Pull request by leonardt**
This provides the initial base class for a transformer visitor.

This implements a polymorphic method `visit` that recursively visits the AST dispatching on the node type.

There is a basic pattern of replacing a node of type T with type T (e.g. replace identifier "x" with identifier "y").  

There is a more complex pattern of replacing an expression with an expression (e.g. replace identifier "x" with expression "z - w".  In this case, the user implements a `visit(std::unique_ptr<Expression> node)` method and dispatches on the runtime type, rather than implementing `visit(std::unique_ptr<Identifier> node)`.  This is because we cannot provide two implementations of `visit(std::unique_ptr<Identifier> node)` (one that returns an Expression and one that returns Identifier). This issue arises when recursively visiting nodes that can have Identifier children, but not Expression children.  Right now the pattern is safe (albeit more verbose for the case when we have to check the Expression type), in that it doesn't allow substituting an Expression for an Identifier in a child that can only be an Identifier (e.g. a declaration of a wire or reg).  So, if the user wants to replace IDs with Expressions, they can only do so inside children where a more general Expression is accepted.

Open to ways on how to make this easier to use (should probably also provide some macros to do the subtype checking), but this functionality will enable inlining of operators in the coreir backend (replace inputs in0/in1 with a symbol/expression).

Also, we make the AST node fields public so that transformers can modify them.

### CODE REVIEW

**Comment by leonardt** [comment]
Also this currently doesn't implement precedence checking for binary operators, but will at least always insert wrapping "( )" for children that are not simple IDs/Nums

**Review by rsetaluri — APPROVED** [review]
Good impl of visitor pattern!

Only suggestion is to move the transformer code into its own file if its not a hassle.

**Comment by leonardt** [comment]
Reorganized into separate header/source, not too familiar with cpp library organization, but does that seem reasonable? (Or should I merge the transformer decl back into a single header for simplicity?)

**Comment by rsetaluri** [comment]
Good to have the header and cpp in different files. LGTM

**Pull request merged**
